[project]
name = "cp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black~=25.1.0",
    "isort~=6.0.1",
    "ruff~=0.12.5",
    "rust-just~=1.42.4",
]
