[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "h", "hpp", "hxx"]
language-servers = ["clangd", "hx-lsp"]
formatter = { command = "clang-format" }
indent = { tab-width = 4, unit = "    " }

[language-server.hx-lsp]
command = "hx-lsp"

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = { command = "black", args = ["-"] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[[language]]
name = "bash"
file-types = ["sh", "bash"]
formatter = { command = "shfmt", args = ["-i", "2"] }
